{% set version = "1.0.0" %}
{% set sha256 = "0f9135eee4cda144c925c59db0b775bb60a679b9e656ad695094c9e9b5635736" %}

package:
  name: message-ix
  version: {{ version }}

source:
  url: https://github.com/iiasa/message_ix/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - messageix-config=message_ix.cli:config
    - messageix-dl=message_ix.cli:dl

requirements:
  build:
    - python
    - pip
  run:
    - ixmp ==0.1.2

test:
  imports:
    - message_ix
  commands:
    - messageix-config -h
    - messageix-dl -h
    - python -c "import ixmp; import message_ix; ixmp.Platform(dbtype='HSQLDB')"

about:
  home: https://github.com/iiasa/message_ix
  license: Apache-2.0
  license_file: LICENSE
  summary: 'The integrated assessment and energy systems model MESSAGEix https://MESSAGEix.iiasa.ac.at/'

extra:
  recipe-maintainers:
    - gidden
