travis:
  secure:
    BINSTAR_TOKEN: IZVq9Yg9S7stmmKWswHiINLordRZoLpPiI1uciY1ZW23qohErsk9qiE1WwgfmQiOiAJobIJB7ZafuD/24cajsGyeDoH/CYbcX7KRUOzHOmncxXELRPezfjCPdsbr14dBMEftAh6dLzKVmsOXQmfcc8aT3M1mUYxj+nta4exy0Sf/BdRpWgh0u/OuyPD6aK8xLbteTm5sgqX7hZSwEwMSjlZ3kSKxgyWKjixGDPH0uRkucx2On/bFLHnr9qvTQuiMdR+32ff0Xo/98nvjI0LPA/ncosiWZK6zTeOyZ9vpg9bPJ8m/CeF9Cl2hJxPnT8uU9a6VisrawwN9KlPconlKj2AovaUHIIP2z00VZffSrje/+UR5AvGUpDnwZgIR/rgmPVLY8lwg8VMye+C15TR/CyYBVZgtpuSSlmmBL5yt7QYL3W+SNeIeiUS8HUxhWKnKz7trpsx7Pmg8X5o8MLWGnXmxa7lYWt4Yaa2Y600JuesLz7A8QpC6zdPICa2+3R1cgAtlfND6WPFhf9fPz7ZzTAQhJdwsj+Xs6B185WidVGJufItwZkF0WcvxwaCrbe4E9YqRTug1B2rypyRGdwgnoZ/Ok5qxwNCjKwbyWOmGADFkjwTgm0j7h0JiFdm9M1tDxmTaCXNkNcNCtAPrDeNl5wQ6v6oeQ3Vi8sfIPRtguN8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
